version: '3'
services:
  app:
    build: .
    command: bin/run_improbed
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
  redis:
    image: redis
    ports:
      - '6379:6379'
    